name: MC-Publish Test
on:
  push:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          github-changelog: |
            **This version is automatically released by CI Build**
            
            Latest commit log:
            
            - ${{ github.event.head_commit.message }}
          github-generate-changelog: true
          github-draft: fals
          github-prerelease: true
          github-tag: dev.${{ github.run_number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
