name: MC-Publish Test
on:
  push:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
