name: CI
on:
  push:
  release:
    types:
      - published
  pull_request:

jobs:
  publish:
    if: ${{ github.event_name == 'release' }}
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the sources
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Print build number
        run: echo ${{ github.event.ref }}
