name: CI
on:
  push:
    branches:
      - 'dev/**'
  release:
    types:
      - published
  pull_request:

jobs:
  publish:
    if: ${{ github.event_name == 'release' }}
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the sources
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Generate build number
        id: buildnumber
        run: |
          echo ${ github.ref_name }
          buildnumber=$(echo ${ github.ref_name } | cut -d . -f3)
          echo "::set-output name=buildnumber::$buildnumber"
      - name: Print build number
        run: echo ${{ steps.buildnumber.outputs.buildnumber }}
