name: workflow call test
on:
  workflow_call:

jobs:
  play:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        run: |
          echo ${{ toJson(github) }}
          exit 0
